import org.testng.annotations.*;

import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertTrue;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library --with testng'
 * by 'Karanjit_Singh' at '9/2/17 4:10 PM' with Gradle 3.1
 *
 * @author Karanjit_Singh, @date 9/2/17 4:10 PM
 */
public class StringReverseTests {
    @DataProvider(name="palindromeCases")
    private Object[][] irrelevantName() {
        return new Object[][] {{"anna"},
                {"kayak"},
                {""},
                {"hannah"}};
    }

    @Test(dataProvider = "palindromeCases")
    public void reversedSometimesIsStillSame(String word) {
        // given
        ReverseString classUnderTest = new ReverseString();

        // when
        final String reverse = classUnderTest.reverse(word);
        // then
        assertEquals(reverse, word);
    }


}
